# Generated by Django 4.2.6 on 2023-11-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='approved',
            new_name='accepted',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
