# Generated by Django 4.2.6 on 2023-11-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_approved_testimonial_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='author_profile',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/'),
        ),
    ]
