# Generated by Django 4.2.6 on 2023-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobb', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='jopspic/'),
            preserve_default=False,
        ),
    ]
